apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hadoop-deployment
  # type: LoadBalancer
  ports:
    - name: port1
      port: 10000
      targetPort: 10000
      nodePort: 30007
      protocol: TCP

    - name: port2
      port: 9870
      targetPort: 9870
      nodePort: 30008
      protocol: TCP

    - name: port3
      port: 8088
      targetPort: 8088
      nodePort: 30009
      protocol: TCP

    - name: port4
      port: 10001
      targetPort: 10001
      nodePort: 30010
      protocol: TCP

    - name: port5
      port: 9000
      targetPort: 9000
      nodePort: 30011
      protocol: TCP

    - name: port6
      port: 6379
      targetPort: 6379
      nodePort: 30012
      protocol: TCP

    - name: port7
      port: 19888
      targetPort: 19888
      nodePort: 30013
      protocol: TCP